# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: customersatisfactionmetrics
  version: "1.1.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/customersatisfactionmetrics-${{ version }}.tar.gz
  sha256: 530912b6fdc61b62f5361bc8500dbd59a0c873a803c932d8db276741a4bc82f3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - django >=3.0

tests:
  - python:
      imports:
        - customersatisfactionmetrics
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: This Django package allows you to create and manage surveys including CSAT, NPS, CES, and Generic Surveys. It supports both anonymous and logged-in user responses with user metadata tracking.
  license: MIT
  license_file: LICENSE
  homepage: http://github.com/pescheckit/customersatisfactionmetrics

extra:
  recipe-maintainers:
    - rxm7706
